export { default as dress } from "./dress.png";
export { default as jacket } from "./jacket.png";
export { default as jeans } from "./jeans.png";
export { default as jeanshorts } from "./jeanshorts.png";
export { default as longsleeve } from "./longsleeve.png";
export { default as scarf } from "./scarf.png";
export { default as shorts } from "./shorts.png";
export { default as skirt } from "./skirt.png";
export { default as sweater } from "./sweater.png";
